# This workflow will call Jenkins to build a Java project with Maven

name: Call Jenkins to build war

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run curl
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          OS: RHEL8
        run: curl -k -u "$JENKINS_USER":"$JENKINS_TOKEN" https://jenkins.sohlberg.io/job/demo-pipeline/buildWithParameters?token="$JENKINS_TOKEN""&OS=${OS}"
