# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@v1.7.1
      with:
        # Request URL
        url: https://jenkins.sohlberg.io/me/my-views/view/all/job/demo-pipeline/build?token=11f83e3e22da79e1276e8747cfb9711ac1
        # Request Method
        method: POST
